name: secure_move
description: Transport ticketing app with QR tickets

environment:
  sdk: '>=3.0.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0      
  intl: ^0.18.0            # date/time formatting
  shimmer: ^3.0.0
  flutter_secure_storage: ^9.2.2
  http: ^1.2.1
  flutter_stripe: ^10.2.0
  mobile_scanner: ^5.0.0
  google_fonts: ^8.0.0
  crypto: ^3.0.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/securemove_bus_hero.png
    - assets/images/securemove_bus_photo.jpg
    - assets/images/securemove_bus_custom.png
